### ISSUE TITLE
Missing pages

### ISSUE THREAD

**Issue by SmookeFR** [yuzu-emu/yuzu-emu.github.io#13]
Hi, this is my first issue. On the website, we can't access to rules page, and the wki button always redirect us to the /home folder. If we change the url to https://yuzu-emu.org/wiki the page have some bugs (css bugs i think). switch homebrew pages, building pages, faq page and switch hardware pages are inacessible. 

List : 
https://yuzu-emu.org/wiki/building-for-linux/
https://yuzu-emu.org/wiki/building-for-windows/
https://yuzu-emu.org/wiki/building-for-macos/
https://yuzu-emu.org/wiki/faq/
https://yuzu-emu.org/wiki/switch-hardware-and-software/
https://yuzu-emu.org/wiki/switch-homebrew

Please guys can you fix it :D

**Comment by chris062689** [comment]
This is now resolved. 

The default listing before was using the style we are going to be using for blogs.
I've adjusted it to be more of a actual list.

https://yuzu-emu.org/wiki/
