### ISSUE TITLE
Download page still talking about old Canary and Mainline

### ISSUE THREAD

**Issue by superheri** [yuzu-emu/yuzu-emu.github.io#149]
This text on the download page should be reviewed since it's not clear which version is which, because we see only one version in the download section and installer.

> Nightly builds are expected to keep maximum accuracy, and therefore, cannot run many commercial titles at the moment. They are mostly useful for development purposes.
> 
> Canary builds contain code that ignores assertions, and makes games run without having implementations of service commands, GPU shaders, etc. In addition to that, Canary might also have features or fixes that have not yet been merged into Nightly.
> 
> Both builds are in constant development, so expect crashes and bugs.
> 
> Since Nightly is less compatible than Canary, we recommend using Canary builds for regular use and issue reporting.
>

**Comment by CaptV0rt3x** [comment]
Fixed.
