### ISSUE TITLE
Cannot access sub-pages from the profile site

### ISSUE THREAD

**Issue by goaaats** [yuzu-emu/yuzu-emu.github.io#150]
*Steps to reproduce:*

1. Log into yuzu profile/citra community(https://profile.yuzu-emu.org/)
2. Click on any of the links in the top bar(blog, download, help, compatibility, wiki, etc)
3. Observe the issue

*Result:*

The page received is not the expected one in the case of blog(goes to / which is the profile page on profile.yuzu-emu.org) and results in 404 errors for the other pages.

**Comment by CaptV0rt3x** [comment]
Thank you for reporting.
This issue has been fixed.
