### ISSUE TITLE
Broken headers/Markdown in Game Modding page

### ISSUE THREAD

**Issue by Margen67** [yuzu-emu/yuzu-emu.github.io#159]
The [Game Modding](https://yuzu-emu.org/help/feature/game-modding/) help page contains markdown, breaking some headers like `### Example`.
This doesn't happen with the Game Modding or Directory Structure headers since they use proper HTML headers.
GitHub link: https://github.com/yuzu-emu/yuzu-emu.github.io/blob/master/help/feature/game-modding/index.html

**Comment by CaptV0rt3x** [comment]
Fixed in #160
