### ISSUE TITLE
[Feature Request] automatic website wiki editing through github wiki

### ISSUE THREAD

**Issue by choppymaster** [yuzu-emu/yuzu-emu.github.io#214]
#### What feature you are suggesting?

A feature where :
when we edit the yuzu's wiki on github, it automatically edits on yuzu's website.

#### How will it affect?

Devs don't have to edit the yuzu's wiki everytime when it updates.

[First time opening an issue, sorry if it looks non professional.]

**Comment by FearlessTobi** [comment]
This is already what's happening.

**Comment by choppymaster** [comment]
My bad. However,

![Screenshot_2020-11-21-07-53-42](https://user-images.githubusercontent.com/74042715/99865377-2db51980-2bcf-11eb-8679-341f18e47708.png)

![Screenshot_2020-11-21-07-53-52](https://user-images.githubusercontent.com/74042715/99865383-39a0db80-2bcf-11eb-978d-91922b45b5b5.png)

When I edit it doesn't edit the wiki.

Is there any missing things? Thanks.

**Comment by Schplee** [comment]
The wiki will only update when the website builds. However, we're aware of an issue with wiki page updates not being pushed to the repo and are working on a fix.

**Comment by choppymaster** [comment]
Ok, thanks! So first I have to edit Github wiki then it will be pushed to website. Ok, will do. Cheers
