### ISSUE TITLE
No space between Title and "Written by"

### ISSUE THREAD

**Issue by CaptV0rt3x** [yuzu-emu/yuzu-emu.github.io#22]
![sd](https://user-images.githubusercontent.com/24495110/42390566-f4288f7e-8169-11e8-957a-ea73fd60c32b.png)
<JMC's Post>

![sd2](https://user-images.githubusercontent.com/24495110/42390568-f63aa3ce-8169-11e8-8f4e-04d668323ad9.png)
<My local test>

**Comment by CaptV0rt3x** [comment]
Fixed by adding <Author> in JSON file.

**Comment by chris062689** [comment]
Is this still an issue?

**Comment by CaptV0rt3x** [comment]
This is still valid if the author's entry isn't present in the JSON file. 
However, since that was, and still is, the intended way, the issue is and always was irrelevant. 😛
