### ISSUE TITLE
Navigating via HTML tags scrolls too far

### ISSUE THREAD

**Issue by lat9nq** [yuzu-emu/yuzu-emu.github.io#239]
When clicking on a link in the site to navigate elsewhere into somewhere on the same page, the page doesn't take into account the size of the navigation bar and instead scrolls directly to the header, leaving the header in the same position as the nav bar as if it weren't there.

For example: https://yuzu-emu.org/wiki/recommended-gpu-drivers-for-linux/#amd

**Comment by CaptV0rt3x** [comment]
I've noticed this when I first tried adding anchors to the quickstart guide. My workaround was to use native html anchor tags instead of depending on hugo to autogenerate them

**Comment by CaptV0rt3x** [comment]
After experimenting for a fair bit, I have come to the conclusion that the way to bypass this would be to add empty `<span>` tag, before every anchor heading, with a css class that is hidden away and offsets the fixed header height.
