### ISSUE TITLE
[Feature Request] - Add Release Version to File Informationen

### ISSUE THREAD

**Issue by stephannn** [yuzu-emu/yuzu-emu.github.io#242]
Hi,
to create a more reliable updater, would it be possible to add the version number to the executable? at the moment the information history is empty:
VersionInfo       : File:             C:\yuzu-windows-msvc\yuzu.exe
                    InternalName:
                    OriginalFilename:
                    FileVersion:
                    FileDescription:
                    Product:
                    ProductVersion:
                    Debug:            False
                    Patched:          False
                    PreRelease:       False
                    PrivateBuild:     False
                    SpecialBuild:     False
                    Language:

BaseName          : yuzu
Target            : {}
LinkType          :
Name              : yuzu.exe
Length            : 17041408

With this information the download url could be verified with the version is already installed.

**Comment by Calinou** [comment]
@stephannn This issue isn't specific to the website, as file information needs to be embedded into the binary at compile-time. This needs to be handled in Yuzu's buildsystem and codebase instead.
