### ISSUE TITLE
RSS feed doesn't give the whole blog post

### ISSUE THREAD

**Issue by fpdotmonkey** [yuzu-emu/yuzu-emu.github.io#299]
Adding the feed `https://yuzu-emu.org/index.xml` to my RSS client as per https://github.com/yuzu-emu/yuzu-emu.github.io/issues/278 sends a message every time there is a new article on the blog, but the message simply consists of the title of the article and a link to the webpage.  I'd like for the whole article to be shipped with the feed.

As well, it'd be nice if there were an RSS button on the blog.

**Comment by adamantike** [comment]
I have created https://github.com/yuzu-emu/shared-bulma-theme/pull/11, which will allow RSS readers to get the full blog posts. Hopefully, it can be merged soon.
