### ISSUE TITLE
For homebrew games, also provide a log for commercial games.

### ISSUE THREAD

**Issue by davidhedlund** [yuzu-emu/yuzu-emu.github.io#354]
I suggest that you instruct people who are submitting logs for homebrew games, to also provide a log for commercial games in https://github.com/yuzu-emu/yuzu/issues/new?assignees=&labels=&projects=&template=bug_report.yml

Reference: https://github.com/yuzu-emu/yuzu/issues/10478#issuecomment-1566007406

**Comment by davidhedlund** [comment]
* https://github.com/yuzu-emu/yuzu/issues/10546

**Comment by FearlessTobi** [comment]
This page does not even mention homebrew games.

**Comment by davidhedlund** [comment]
> This page does not even mention homebrew games.

You probably need to practice your politeness a bit instead of closing issues immediately. You don't think I opened this issue because I requested you to _add_ some text about homebrew games to the page?
