### ISSUE TITLE
Implement the Gitpod Ready-to-code service

### ISSUE THREAD

**Issue by Panquesito7** [yuzu-emu/yuzu-emu.github.io#362]
### Description

By implementing the Gitpod Ready-to-code service, everyone will be able to deploy and test the page in one single click without installing any dependencies.
This will make it a lot easier for beginners or those that do not have the necessary tools to build the page.

For more information: https://www.gitpod.io/

**Comment by FearlessTobi** [comment]
I don't think we really need this.
The purpose of the website is mainly for internal use by the yuzu team, and we all know how to build it.

Feel free to open a Pull Request for this though if you think it is important.

**Comment by Panquesito7** [comment]
It doesn't really harm adding it, though.
If wanted, I could create a PR to add it, it's pretty easy.
