### ISSUE TITLE
Compatibility link from the header is 404

### ISSUE THREAD

**Issue by NetSysFire** [yuzu-emu/yuzu-emu.github.io#369]
Steps to reproduce:

1. Go to the website.
2. Click Compatibility in the header, which links to https://yuzu-emu.org/game
3. It is 404.

Expected behavior:

It is not 404. I looked around in the repo here but can not find any traces to where the link target might have gone. It was likely simply renamed and someone forgot to change it in the header.

**Comment by FearlessTobi** [comment]
fixed.

**Comment by NetSysFire** [comment]
I am afaid this is happening again.

**Comment by NetSysFire** [comment]
And again.
