### ISSUE TITLE
Broken Game Compatibility List

### ISSUE THREAD

**Issue by Champe20** [yuzu-emu/yuzu-emu.github.io#372]
Since the [27th or 28th according to archive.org](https://web.archive.org/web/20230928203441/https://yuzu-emu.org/game/), the game compatibility list has been broken and [returns a 404 error](https://yuzu-emu.org/game).

**Comment by YassineHaouzane** [comment]
It seems to be broken again, the last time that it was working properly was the 21th october according to [archive.org](https://web.archive.org/web/20231021183937/https://yuzu-emu.org/game/)
