### ISSUE TITLE
Can't create or edit wiki pages

### ISSUE THREAD

**Issue by DraakjeYoblama** [yuzu-emu/yuzu-emu.github.io#373]
I'm writing the issue here, because that repo doesn't allow issues.

The button to edit the [wiki](https://github.com/yuzu-emu/yuzu-games-wiki) seems to be gone.
As a result, some games don't have a wiki entry and give a 404 page on the website (for example [Kirby and the Forgotten Land](https://yuzu-emu.org/game/kirby-and-the-forgotten-land))

**Comment by FearlessTobi** [comment]
We sadly had to restrict our wiki due to vandalism.
