### ISSUE TITLE
Compatibility page leads to 404 page

### ISSUE THREAD

**Issue by YassineHaouzane** [yuzu-emu/yuzu-emu.github.io#379]
The url https://yuzu-emu.org/game leads to a 404 page, the last time that it was working properly was the 21th october according to [archive.org](https://web.archive.org/web/20231021183937/https://yuzu-emu.org/game/).

This doesn't seem the first time that it has happened. 
I have investigated and I think this comes from the fact that in the `shared-hugo-scripts` the build won't fail even if we can't fetch the compatibility data from the [api](https://api.yuzu-emu.org/gamedb/websiteFeed/). 

Maybe the task should fail if we can't fetch the data from the api ?

**Comment by G-Spawn** [comment]
It's being reworked. It's currently up but expect it to be downed every now and again during the process of it being improved 🙏
