### ISSUE TITLE
404 on /game

### ISSUE THREAD

**Issue by Klebestreifen** [yuzu-emu/yuzu-emu.github.io#387]
https://yuzu-emu.org/game is responsing 404

**Comment by spanic** [comment]
@Klebestreifen I guess everything is fine for now, you can double-check & close the issue if it's not reproducible anymore. 

<img width="1840" alt="Screenshot 2024-01-29 at 01 05 08" src="https://github.com/yuzu-emu/yuzu-emu.github.io/assets/15694775/7658020e-0b21-4f80-95ff-89903b121ef4">
