### ISSUE TITLE
Game compatibility incorrect order

### ISSUE THREAD

**Issue by superheri** [yuzu-emu/yuzu-emu.github.io#65]
The game ordering in the list is not working correctly. the two Pokemon Let's Go should be together since they're names start the same way, but this is actually not the case.

![image](https://user-images.githubusercontent.com/30275781/49873092-018c9d80-fde9-11e8-8074-e6979863f2a4.png)

**Comment by j-selby** [comment]
![nicepint](https://user-images.githubusercontent.com/1404334/49909966-18102300-fed5-11e8-9ad0-35393fde7dfe.png)

Unable to replicate. Do you have Javascript enabled?

**Comment by superheri** [comment]
It seems fixed strangely. I don't know what happened exactly, was using Opera with Private Mode enabled. I can't reproduce it myself too... I don't know what happened. Sorry for the inconvenience.
